export const projects = [
  {
    title: '1. DEPOP REDESIGN',
    description: "A web redesign focused on improving price-comparison functionalities on secondhand e-commerce webistes to encourage sustainable shopping",
    image: ' ',
    tags: ['React', 'WebRTC'],
    // source: 'Pages/Kini',
    source: 'https://medium.com/@pei.rainee/depop-redesign-73b1e2f7d8c5',
    id: 0,
  },
  {
    title: '',
    description: "",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://apple.com',
    id: 1,
  },
  {
    title: '2. KINI KOFFEE',
    description: "UX Researcher for the design and development of a website for women-led coffee shop, Kini Koffee.",
    image: ' ',
    tags: ['React', 'WebRTC'],
    source: 'Pages/Kini',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: '3. SDSC - LOANE',
    description: "Design and development of a student loans and budgeting app aimed to help students transition into financial independence. My first design and software engineering internship :-)",
    image: ' ',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'Pages/Loane',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: '',
    description:"",
    image: ' ',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: '4. ANALOG',
    description: "film snapshots ",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'Pages/Analog',
    visit: 'https://google.com',
    id: 6,
  },
];

export const about = [
  {
    title: '',
    image: '/images/aboutPhoto.jpeg',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'Loane',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    image: ' ',
    description:"what's up!",
    description1: "rainee is currently a student at uc san diego double majoring in bioinformatics and cognitive science: design and interaction.",
    description2: "she's passionate about the intersection of tech and design and is always looking for opportunities to engage in both creative and technical work.",
    description3: "in her free time, she loves to shoot film, climb, and skateboard. she also loves her slightly chunky cat, dally.",
    tags: ['React', 'JavaScript'], 
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  }
];