export const projects = [
  {
    title: '1. SDSC - LOANE',
    description: "Design and development of a student loans and budgeting app aimed to help students transition into financial independence. My first software engineering and design internship :-)",
    image: ' ',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description:"",
    image: ' ',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: '2. MISCELLANEOUS',
    description: "projects a la carte",
    image: ' ',
    tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: '3. ANALOG',
    description: "film snapshots ",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];