export const projects = [
  {
    title: '1. SDSC - LOANE',
    description: "Design and development of a student loans and budgeting app aimed to help students transition into financial independence. My first software engineering and design internship :-)",
    image: ' ',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'Pages/Loane',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description:"",
    image: ' ',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: '2. MISCELLANEOUS',
    description: "projects a la carte",
    image: ' ',
    tags: ['React', 'WebRTC'],
    source: 'Pages/Misc',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: '3. ANALOG',
    description: "film snapshots ",
    image: ' ',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'Pages/Analog',
    visit: 'https://google.com',
    id: 4,
  },
];

export const about = [
  {
    title: '',
    image: '/images/aboutPhoto.jpeg',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'Loane',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    image: ' ',
    description:"what's up!",
    description1: "rainee is currently a student at uc san diego double majoring in bioinformatics and cognitive science: design and interaction.",
    description2: "she's passionate about the intersection of tech and design and is always looking for opportunities to engage in both creative and technical work.",
    description3: "in her free time, she loves to skateboard, shoot film, and embroider. she also loves her slightly chunky cat, dally.",
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  }
];